### ISSUE TITLE
Find Duplicates part not working

### ISSUE THREAD

**Issue by DaviJh** [Maximax67/LoRA-Dataset-Automaker#10]
![image](https://github.com/user-attachments/assets/7773622b-80fe-4bc9-8dd6-13904ddf7561)
Before the error says alot msg cannot identify image

**Comment by melMass** [comment]
@Maximax67 The issue comes from PIL being unable to decode the images (I don't know why I even tried to copy them to the root of the notebook to be sure it wasn't a path thing). So it returns a list of None (`[None,None,None...]`)

I couldn't track any related issue upstream (in Pillow) and naively tried to downgrade to a version based on your last commit date and it now works.

In cell 2 replace `!pip install Pillow` with `!pip install Pillow==9.4.0`

**Comment by Maximax67** [comment]
I fixed the problem. I downgraded Pillow to 9.5.0 and rolled back to the previous git yolov5 commit where this version was supported. @melMass, thanks for the hint. There is also a strange behavior in Pillow. If I replace it with `!pip install Pillow==9.5.0`, google colab will ask to restart the session, because Pillow was already imported even if it's a new session. So I duplicated the pip install line twice, and now everything works.
